### ISSUE TITLE
KbWriteProcessMemory BSOD

### ISSUE THREAD

**Issue by adspro15** [HoShiMin/Kernel-Bridge#1]
After last update KbWriteProcessMemory get BSOD some time later "Process Locked ..."
Previously, everything worked

**Comment by HoShiMin** [comment]
@adspro15, what BSOD status are you get?

**Comment by adspro15** [comment]
@HoShiMin does not write memory

**Comment by HoShiMin** [comment]
@adspro15, but what status code (or reason) of BSOD are you get?

**Comment by adspro15** [comment]
@HoShiMin bsod i got randomly when tried cycle write memory,now there is no bsod,but not write memory

**Comment by HoShiMin** [comment]
@adspro15, well, I'll check it

**Comment by HoShiMin** [comment]
Fixed
