### ISSUE TITLE
CommPortListener Events

### ISSUE THREAD

**Issue by Wrath-debug** [HoShiMin/Kernel-Bridge#10]
CommPortListener Events are never called, it stuck in Subscribe function.
I tried to debug the problem , it's something in this line 
" Status=Self>Port.Recv(*reinterpret_cast<CommPortPacket*>(&Message));"
in ListenerThread function

any ideas what could be the problem ?
P.S : same problem is happening for TestObCallbacks event listener never called

**Comment by HoShiMin** [comment]
It seems that now it is fixed
