### ISSUE TITLE
Unable to load driver!

### ISSUE THREAD

**Issue by CaptainCliff** [HoShiMin/Kernel-Bridge#11]
Hey,

if I run the test I always get the message "Unable to load driver!". I adjusted the path for the kernel-bridge.sys but the issue still persists?

Am I doing sth wrong?

Best regards!

**Comment by HoShiMin** [comment]
Whether the HVCI/DeviceGuard with only WHQL-only policies is disabled?
If you unable to load a signed driver - it seems that DeviceGuard is blocks it.

**Comment by CaptainCliff** [comment]
Stupid mistake from me. Sorry for bothering.
