### ISSUE TITLE
building Reading process memory project

### ISSUE THREAD

**Issue by qazxsw1597532018** [HoShiMin/Kernel-Bridge#15]
3 errors preventing me from building Reading process memory 

> #include <Windows.h>
#include "WdkTypes.h"
#include "CtlTypes.h"
#include "User-Bridge.h"
int main()
{
    using namespace KbLoader;
    // Unloading previous loaded instance:
    KbUnload();
    BOOL Status = KbLoadAsFilter(
        L"C:\\Users\\Admin\\Downloads\\Kernel-Bridge\\x64\\Release\\Kernel-Bridge.sys",
        L"260000" // Altitude of minifilter
    );
    if (!Status)
        return 0; // Unable to load driver!
    // Successfully loaded!
    // Now you can use the User-Bridge API! 
        KbUnload();
    return 0;
}

> Error	LNK2001	unresolved external symbol "int __cdecl KbLoader::KbLoadAsFilter(wchar_t const *,wchar_t const *)" (?KbLoadAsFilter@KbLoader@@YAHPEB_W0@Z)	MyProject	C:\Users\Admin\Downloads\Kernel-Bridge-master\MyProject\MyProject.obj	1	

> Error	LNK2001	unresolved external symbol "int __cdecl KbLoader::KbUnload(void)" (?KbUnload@KbLoader@@YAHXZ)	MyProject	C:\Users\Admin\Downloads\Kernel-Bridge-master\MyProject\MyProject.obj	1	

> Error	LNK1120	2 unresolved externals	MyProject	C:\Users\Admin\Downloads\Kernel-Bridge-master\x64\Release\MyProject.exe	1

**Comment by qazxsw1597532018** [comment]
I'm still trying for hours how to use this framework but without success, can please explain how to get started with the framework.
I'm trying to make a driver that read a process memory and communicate with another process, or to be precise : driver receive request form program A to read memory of program B.
Thank you very much!

**Comment by HoShiMin** [comment]
Are you trying to use it with User-Bridge.dll or with User-Bridge sources directly?

**Comment by qazxsw1597532018** [comment]
I'm trying to use it with User-Bridge sources.
