### ISSUE TITLE
Not initialized request variable

### ISSUE THREAD

**Issue by boris768** [HoShiMin/Kernel-Bridge#16]
https://github.com/HoShiMin/Kernel-Bridge/blob/master/User-Bridge/API/User-Bridge.cpp#L507
https://github.com/HoShiMin/Kernel-Bridge/blob/master/User-Bridge/API/User-Bridge.cpp#L565

KbMapMdl and KbMapMemory funcs have UserRequestedAddress arg, but it is not passed to KB_MAP_MDL_IN Input struct.

**Comment by HoShiMin** [comment]
Fixed. Thanks for reporting.
