### ISSUE TITLE
Do you know how to implement a ring0 debugger?

### ISSUE THREAD

**Issue by avalon1337** [HoShiMin/Kernel-Bridge#17]
How does one implement a system where one can read register values between each instruction?
Hypervisor? Callbacks?

Thank you!

**Comment by HoShiMin** [comment]
@avalon1337 Yes, you can implement a kernel debugger using a hypervisor and your own int3-handler (handler of breakpoint). You should overwrite an existing handler in IDT and hide this modification from PatchGuard by hypervisor. It is the most simple way to debug instructions one-by-one.

**Comment by marcussacana** [comment]
@HoShiMin I don't wanted create an issue just to do a question, this issue make me think, is possible run a proccess with an fake cpuid without use Virtual machines?, maybe run a program with hypervisor...?
In the true I have no need to fake my cpuid, but this make me think, how hard is to fake the cpuid? since we have many programs that use this instruction to fingerprint the computer...

**Comment by HoShiMin** [comment]
@marcussacana, only way to change CPUID is use hypervisor (hypervisor and virtual machine is the same thing). If you want top do it, you should write a hypervisor using AMD-V/RVI or VT-x/EPT depending on your processor. And then you can catch #VMEXIT on CPUID call and change all registers you want:
[https://wasm.in/attachments/05-01-2019-22-52-48-png.4425/](url)

**Comment by marcussacana** [comment]
Interesting, I always thought of hyper-v as a hardware-level sandbox... but in the end it is equivalent to a VM...

**Comment by HoShiMin** [comment]
@marcussacana, exactly. Hyper-V/ESXi/Citrix are Type-1 hypervisors (running directly on the system hardware - your 'host' Windows with enabled Hyper-V works under hypervisor), VMware/VirtualBox/KVM/etc. - are Level-2 hypervisors (running on a host OS). For your task is more convinient to develop a Type-2 hypervisor (just a Windows driver) and virtualize an already running OS.

**Comment by marcussacana** [comment]
I see, that clarifies my doubts, you even looked like an encyclopedia now :) thanks for your patience.

**Comment by HoShiMin** [comment]
@marcussacana, you're welcome ^_^
