### ISSUE TITLE
BSOD in DriverControl

### ISSUE THREAD

**Issue by Eran-YT** [HoShiMin/Kernel-Bridge#19]
I tried to load the driver as a filter, and immediately got a blue screen, from some debugging, I found the bug in the DriverControl function, in line 311:
```
 IoCompleteRequest(Irp, IO_NO_INCREMENT);
 return Irp->IoStatus.Status;
``` 
The Irp variable is used after IoCompleteRequest, which should not be done (according to google)

**Comment by HoShiMin** [comment]
Fixed, binaries was updated. Thanks for reporting.
