### ISSUE TITLE
Forcing the processor to chew 1 instruction (ring0)

### ISSUE THREAD

**Issue by avalon1337** [HoShiMin/Kernel-Bridge#20]
Do you know how to make the processor chew a single instruction? What function would I look at?

**Comment by HoShiMin** [comment]
There are no 'functions' in kernel to achieve what you want.
If you talk about instruction-by-instruction execution, you should write a hypervisor that traps the int3 or single-step interrupts (caused by the trap-flag in EFLAGS).
