### ISSUE TITLE
KbFindSignature Failing

### ISSUE THREAD

**Issue by SoftCrush** [HoShiMin/Kernel-Bridge#21]
There are some memory regions where this function seems to fail (returns 0), whereas other memory regions seem to work fine. Any idea as to why this is happening or if there is a possible fix?

The same memory regions that KbFindSignature fails on KbReadProcessMemory also fails.

**Comment by HoShiMin** [comment]
Does these 'bad' regions differ from 'good' regions? What rights did they have?
