### ISSUE TITLE
Delphi API ?

### ISSUE THREAD

**Issue by chmichael** [HoShiMin/Kernel-Bridge#22]
Hello,
  Any chance for a Delphi API to access this beautiful library ?

Thank you

**Comment by HoShiMin** [comment]
Not yet, but who knows...
Anyway, you can write it yourself and send me a pull request

**Comment by marcussacana** [comment]
I already wanted create one to C# before, well, I stopped when I saw a little complex struct (EPocess if i'm not wrong, there are some bitfields and the C# don't support it), the structure is very big and I tried to implement, If i remember I even listed all fields of all sub structures, but I stopped when the thing came to implement the bitfields... well, whatever, but to you accept a pull request you have any requeriments?

**Comment by HoShiMin** [comment]
@marcussacana 
Well, if you want to implement bitfields without support in language (like in C#), you can use bit masks (just AND'ing or OR'ing the value with the mask):  
```
int value = 0x123;
int mask = 4; // 0b100 (bits counting started with 0)

// Is bit set:
bool is2ndBitSet = (value & mask) == mask;

// Set the bit:
value |= mask;

// Reset the bit:
value &= ~mask;
```
You can use this stuff if you need it.  
And what about pull requests - I accept them if they're well-coded and convenient, but without any special requirements.  
So, you're welcome! 😉

**Comment by marcussacana** [comment]
I see, haha, don't care, i'm not newbie enough to don't know bitwise operations, it's just that problem with the bitwise struct... well maybe I can give a try a day, thx for the information.

**Comment by chmichael** [comment]
Delphi Connector: https://github.com/diversenok/Kernel-Bridge-Delphi-Connector
