### ISSUE TITLE
C++ exception handling is not supported with /kernel

### ISSUE THREAD

**Issue by AndyWatterman** [HoShiMin/Kernel-Bridge#36]
Trying to include "CppSupport.h" from your project, but these errors occur:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2980	C++ exception handling is not supported with /kernel	MyDriver1	C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\km\crt\exception	72	
Error	C2146	syntax error: missing ';' before identifier '_Raise_handler'	MyDriver1	C:\Sources\My\MyDriver1\MyDriver1\CppSupport.cpp	227	
Error	C2980	C++ exception handling is not supported with /kernel	MyDriver1	C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\km\crt\exception	72	
```

It shows and error at the following code:
```
_Prhand _Raise_handler = &RaiseHandler;
```

Could you help me, please, how to solve these errors?

**Comment by HoShiMin** [comment]
Check what is the _HAS_EXCEPTIONS macro equal to? It defined in vcruntime.h. It must be equal 0.

**Comment by SLIpros** [comment]
@crowman2 
![2021-07-31_14-33-45](https://user-images.githubusercontent.com/6332783/127738643-41e8f8cf-c544-40f4-8975-e1a62785f39c.png)

**Comment by AndyWatterman** [comment]
> @crowman2
> ![2021-07-31_14-33-45](https://user-images.githubusercontent.com/6332783/127738643-41e8f8cf-c544-40f4-8975-e1a62785f39c.png)

**Comment by AndyWatterman** [comment]
Includes solve the problem. Thanks.
