### ISSUE TITLE
signed binaries can not be loaded 

### ISSUE THREAD

**Issue by danyhm** [HoShiMin/Kernel-Bridge#40]
Hello,

I tried loading the signed binaries but i get the message "a certificate was explicitly revoked by its issuer"

**Comment by danyhm** [comment]
I see that the binaries were signed using leaked certs :)
so updated windows won't allow loading them. I've tried other leaked certs as well.

just one question. since the revocation status is determined but CRL or OCSP and those are provided by CAs in an online matter , is it possible to somehow clear those revocation status temporarily and then load the driver?

**Comment by danyhm** [comment]
unfortunately, that's not possible in my case.
Actually I stumbled across Kernel-Bridge while searching for ways to load my driver which is actually a hypervisor based on hvpp
and i see you also support hypervisor for both Intel and AMD ! that's pretty cool. I hope you keep this project alive.

**Comment by HoShiMin** [comment]
@danyhm, sure, I work for the Kb2 now and it will be released... one day. But it is the problem with binary signing as it requires to have a valid EV cert with recent Microsoft signing policies update.

**Comment by danyhm** [comment]
@HoShiMin I hope you can get the binaries signed. although I think Microsoft won't sign them as it's against their policies to mess with their kernel.
however, If you could get them signed, I recommend you provide the signed binaries as a pro option with payment. this way
you can make some money and control who has access to the signed binaries so They can't be used to load malware.
also, a simple licensing system will make sure the signed binaries can't be leaked

**Comment by HoShiMin** [comment]
@danyhm, maybe, but for now you could use leaked nVidia cert. It isn't blocked yet.

**Comment by ALEHACKsp** [comment]
I can't compile this driver on the visual Studio 2022,what happened?

**Comment by HoShiMin** [comment]
@ALEHACKsp, what error do you have?
