### ISSUE TITLE
add APIs

### ISSUE THREAD

**Issue by nblog** [HoShiMin/Kernel-Bridge#41]
hi, 
i want to add api, not sure if it is planned?
like: 
[NtWaitForSingleObject](https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntwaitforsingleobject) (wait for create thread)
[NtQueryVirtualMemory](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntqueryvirtualmemory)

**Comment by HoShiMin** [comment]
Hm, well, I'll add them to the Kb2
