### ISSUE TITLE
KbWriteProcessMemory 

### ISSUE THREAD

**Issue by liwei1024** [HoShiMin/Kernel-Bridge#43]
KbWriteProcessMemory writes to a static address, reopening the process will not restore the previous data

**Comment by HoShiMin** [comment]
Hm, what do you mean?

**Comment by liwei1024** [comment]
> 嗯，什么意思？

I modified the value of an address of another process, and then restarted the process, the value of that address is still the data I wrote before

**Comment by liwei1024** [comment]
My English is not good, I used google translate

**Comment by HoShiMin** [comment]
It seems you wrote in the shared page. These writings don't trigger copy-on-write. You should make these pages resident using ZwProtectVirtualMemory before write to them.

**Comment by liwei1024** [comment]
好的，感谢您的快速恢复。
