### ISSUE TITLE
How to use the hypervisor to change the CPUID values?

### ISSUE THREAD

**Issue by danyhm** [HoShiMin/Kernel-Bridge#45]
Hello,

I've looked at the hypervisor API, however, It only starts and stops the virtualization. How is it possible to catch a CPUID instruction while the hypervisor is running and change the result values?
is this possible with the API or source code change is needed?

**Comment by marcussacana** [comment]
As far I know, the hypervisor can't run a certain process to you just control, I think you will need to implement something like a bootloader that run the entire system behind the hypervisor, then you will be able to do things like that.
Well, not sure, I never worked with hypervisor after all, therefore I can be wrong, then let's wait the response of someone that really know.

**Comment by danyhm** [comment]
it's absolutely possible without a bootloader. here's an example https://github.com/wbenny/hvpp/
however I don't know how to do it with KB
