### ISSUE TITLE
Try using the serialization library based on your CppSupport

### ISSUE THREAD

**Issue by liwei1024** [HoShiMin/Kernel-Bridge#59]
alpaca::serialize can be successfully executed

alpaca::deserialize Execution fails

Could you take a look

[[https://github.com/p-ranav/alpaca](url) #](url)

**Comment by liwei1024** [comment]
#include <ntddk.h>
#include "CppSupport.h"
#include "include/alpaca/alpaca.h"

#define klog(Format, ...) DbgPrint(("klog: " Format "\n"), __VA_ARGS__) 

struct S1
{
	std::string v1;
	std::string v2;
};


VOID DriverUnload(PDRIVER_OBJECT DriverObject) {
	__crt_deinit();
}

EXTERN_C NTSTATUS DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegisterPtah){

	__crt_init();

	UNREFERENCED_PARAMETER(DriverObject);
	UNREFERENCED_PARAMETER(RegisterPtah);

	S1 s1 = {};
	s1.v1 = "123456";
	s1.v2 = "654321";

	std::vector<uint8_t> bytes;
	auto bytes_written = alpaca::serialize(s1, bytes);


	std::errc ec;
	auto des = alpaca::deserialize<S1>(bytes, ec);

	klog("v1 %s\n", des.v1.c_str());
	//klog("v2 %s\n", des.v2.c_str());
	klog("ec %d\n", static_cast<int>(ec));


	DriverObject->DriverUnload = DriverUnload;
	return 0;
}

**Comment by HoShiMin** [comment]
So, what's wrong with alpaca? What fails in deserialization?

**Comment by liwei1024** [comment]
> 那么，alpaca 到底出了什么问题？反序列化失败的原因是什么？



> So, what's wrong with alpaca? What fails in deserialization?

The error code is argument_list_too_long

The same code will work in R3
